import { createEnum } from '../CompilerLib/helpers';

export const nodeTypes = createEnum([
  'Empty',
  'Root',
  'Block',
  'Expression',
  'Term',
  'Print',
  'Call',
  'CallTerm',
  'Number',
  'String',
  'Add',
  'Subtract',
  'UMinus',
  'Multiply',
  'Divide',
  'Paren',
  'VariableDim',
  'Dim',
  'Clone',
  'FunctionDecl',
  'FunctionCall',
  'FunctionReturn',
  'FunctionTerm',
  'ModuleTerm',
  'VariableList',
  'ExpressionList',
  'ArrayList',
  'ArrayLookup',
  'Assign',
  'ArrayAssign',
  'And',
  'Or',
  'Not',
  'Relation',
  'Equals',
  'NotEquals',
  'LessThan',
  'GreaterThan',
  'LessThanEqualTo',
  'GreaterThanEqualTo',
  'While',
  'If',
  'For',
  'In',
  'To',
  'Variable',
  'PropertyAssign',
  'PropertyTerm',
  'PropertyMethodCall',
  'PropertyMethodTerm',
  'ConstructorDecl',
  'TypedArrayDim',
]);

export default nodeTypes;
