const getMonacoConfig = (): any => ({
  tokens: [
    [/dim/i, "custom-keyword"],
    [/print/i, "custom-function"],
    [/call/i, "custom-function"],
    [/onupdate/i, "custom-event"],
    [/onkeydown/i, "custom-event"],
    [/onpointerdown/i, "custom-event"],
    [/onpointermove/i, "custom-event"],
    [/while/i, "custom-keyword"],
    [/endwhile/i, "custom-keyword"],
    [/if/i, "custom-keyword"],
    [/endif/i, "custom-keyword"],
    [/for/i, "custom-keyword"],
    [/in/i, "custom-keyword"],
    [/next/i, "custom-keyword"],
    [/function/i, "custom-keyword"],
    [/return/i, "custom-keyword"],
    [/endfunction/i, "custom-keyword"],
    [/and/i, "custom-keyword"],
    [/or/i, "custom-keyword"],
    [/not/i, "custom-keyword"],
    [/"(.*?)"/, "custom-literal"],
    [/'.*/, "custom-comment"],
  ],
  theme: {
    base: "vs",
    inherit: true,
    colors: {
      "editor.foreground": "#BDAE9D",
      "editor.background": "#2A211C",
      "editor.selectionBackground": "#C3DCFF",
      "editor.lineHighlightBackground": "#3A312C",
      "editor.highlightBackground": "#9a4a9c88",
      "editorCursor.foreground": "#889AFF",
      "editorWhitespace.foreground": "#BFBFBF",
      "editorIndentGuide.background": "#5e81ce52",
      "editor.selectionHighlightBorder": "#122d42",
      editorIndentGuides: "#D3D3D3",
      editorActiveIndentGuides: "#939393",
      "editor.inactiveSelectionBackground": "#ff000066",
      "editor.selectionHighlight": "#00ff0066",
    },
    rules: [
      { token: "custom-keyword", foreground: "000080" },
      { token: "custom-function", foreground: "008000" },
      { token: "custom-event", foreground: "005000" },
      {
        token: "custom-comment",
        foreground: "666666",
        fontStyle: "italic",
      },
      { token: "custom-literal", foreground: "660000", fontStyle: "italic" },
    ],
  },
});

export default getMonacoConfig;
