const getMonacoConfig = (): any => ({
  tokens: [
    [/class/i, "custom-keyword"],
    [/dim/i, "custom-keyword"],
    [/clone/i, "custom-keyword"],
    [/print/i, "custom-function"],
    [/call/i, "custom-function"],
    [/onupdate/i, "custom-event"],
    [/onkeydown/i, "custom-event"],
    [/onpointerdown/i, "custom-event"],
    [/onpointermove/i, "custom-event"],
    [/while/i, "custom-keyword"],
    [/endwhile/i, "custom-keyword"],
    [/if/i, "custom-keyword"],
    [/endif/i, "custom-keyword"],
    [/for/i, "custom-keyword"],
    [/in/i, "custom-keyword"],
    [/next/i, "custom-keyword"],
    [/function/i, "custom-keyword"],
    [/return/i, "custom-keyword"],
    [/endfunction/i, "custom-keyword"],
    [/and/i, "custom-keyword"],
    [/or/i, "custom-keyword"],
    [/not/i, "custom-keyword"],
    [/"(.*?)"/, "custom-literal"],
    [/'.*/, "custom-comment"],
  ],
  theme: {
    base: "vs-dark",
    inherit: true,
    colors: {
      "editor.background": "#0b0b18",
      "editor.foreground": "#e0e0f0",
      "editor.lineHighlightBackground": "#12122a",
      "editor.selectionBackground": "#3030aa55",
      "editorCursor.foreground": "#6060dd",
      "editorLineNumber.foreground": "#4a4a88",
      "editorLineNumber.activeForeground": "#8888bb",
      "editor.inactiveSelectionBackground": "#1e1e4440",
      "editorIndentGuide.background": "#2a2a55",
      "editorIndentGuide.activeBackground": "#6060dd",
      "scrollbar.shadow": "#0b0b18",
      "scrollbarSlider.background": "#2a2a5566",
      "scrollbarSlider.hoverBackground": "#3030aa88",
    },
    rules: [
      { token: "custom-keyword", foreground: "8080ff", fontStyle: "bold" },
      { token: "custom-function", foreground: "40aa60" },
      { token: "custom-event", foreground: "cc9933" },
      {
        token: "custom-comment",
        foreground: "4a4a88",
        fontStyle: "italic",
      },
      { token: "custom-literal", foreground: "cc8866", fontStyle: "italic" },
    ],
  },
});

export default getMonacoConfig;
