import { Tree } from '@CompilerLib/tree';
import nodeTypes from '../nodeTypes';
import type { SourceLocation } from '@CompilerLib/compiler/types';

// The `data.module` payload is retained only for debug identification / AST
// inspection — emission never reads it (ConstBlockRule returns '' and the
// frozen holder is generated by the symbol-table-driven `constantRules` pass).
class ConstBlockNode extends Tree {
  constructor(data: { module: string }, loc?: SourceLocation) {
    super(nodeTypes.ConstBlock, data, []);
    this.loc = loc;
  }
}

export default ConstBlockNode;
