/**
 * Deterministic stress-scene generator for the raycaster Phase 9 benchmark.
 *
 *   npx vite-node scripts/genRaycasterStress.ts
 *
 * Writes stress16/32/48 .stm + enemy spawn lists + a shared camera path into
 * demo-src/raycaster-p9-bench/assets/. No RNG — placement is a pure function of
 * cell coordinates, so the benchmark is stable run to run.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const OUT = 'demo-src/raycaster-p9-bench/assets';
const SIZES = [16, 32, 48];
const FCOLS = ['6b3f22', '394c2f', '35608a'];
const CCOLS = ['2f3a52', '4a2f3a', '2f4a3a'];
const TEXES = ['rc_tex_brick.png', 'rc_tex_panel.png', 'rc_tex_rock.png'];

interface Marker {
  row: number;
  col: number;
  tag: string;
}

function buildStm(n: number) {
  // walls grid: solid border, open interior
  const walls: number[][] = [];
  for (let r = 0; r < n; r++) {
    const row: number[] = [];
    for (let c = 0; c < n; c++) {
      row.push(r === 0 || c === 0 || r === n - 1 || c === n - 1 ? 1 : 0);
    }
    walls.push(row);
  }

  const markers: Marker[] = [];
  // interior 4x4 motif
  for (let r = 1; r < n - 1; r++) {
    for (let c = 1; c < n - 1; c++) {
      const br = r % 4;
      const bc = c % 4;
      const blk = Math.floor(r / 4) + Math.floor(c / 4);
      if (br === 0 && bc === 0) markers.push({ row: r, col: c, tag: 'floor:0.4 ceil:2.0' });
      else if (br === 1 && bc === 1) markers.push({ row: r, col: c, tag: 'floor:-0.6' });
      else if (br === 2 && bc === 2) markers.push({ row: r, col: c, tag: 'diag:se' });
      else if (br === 0 && bc === 2) markers.push({ row: r, col: c, tag: `fcol:${FCOLS[blk % 3]}` });
      else if (br === 2 && bc === 0) markers.push({ row: r, col: c, tag: `ccol:${CCOLS[blk % 3]}` });
      else if (br === 3 && bc === 3) {
        walls[r][c] = 1;
        markers.push({ row: r, col: c, tag: `tex:${TEXES[blk % 3]}` });
      }
    }
  }
  // border wall textures, ~1 in 3
  for (let c = 0; c < n; c++) {
    if (c % 3 === 0) {
      markers.push({ row: 0, col: c, tag: `tex:${TEXES[c % 3]}` });
      markers.push({ row: n - 1, col: c, tag: `tex:${TEXES[(c + 1) % 3]}` });
    }
  }

  return {
    walls,
    stm: {
      tileWidth: 16,
      tileHeight: 16,
      tileImage: 'rc_placeholder_tiles.png',
      layers: { walls, tags: { type: 'markers', markers } },
    },
  };
}

function buildEnemies(n: number, walls: number[][]) {
  const out: Array<{ x: number; y: number }> = [];
  for (let r = 3; r < n - 2; r += 6) {
    for (let c = 3; c < n - 2; c += 6) {
      // skip solid wall cells (border + wall-stub motif cell) so spawns never
      // land embedded in geometry and get depth-clipped away
      if (walls[r][c]) continue;
      // avoid the pit motif cell so spawns land on standard floor
      if (r % 4 === 1 && c % 4 === 1) continue;
      out.push({ x: c + 0.5, y: r + 0.5 });
    }
  }
  return out;
}

// Camera path authored in stress32 coordinates; the harness scales by n/32.
function buildPath() {
  const wp: Array<{ x: number; y: number; angle: number }> = [];
  const pts: Array<[number, number]> = [
    [2, 2], [8, 3], [8, 10], [3, 14], [10, 16], [16, 12],
    [16, 20], [22, 22], [28, 18], [29, 28], [20, 29], [12, 24], [4, 28], [2, 20],
  ];
  for (let i = 0; i < pts.length; i++) {
    const [x, y] = pts[i];
    const [nx, ny] = pts[(i + 1) % pts.length];
    const angle = Math.atan2(ny - y, nx - x);
    // 3 sub-waypoints per leg → ~42 frames
    for (let s = 0; s < 3; s++) {
      const t = s / 3;
      wp.push({ x: x + (nx - x) * t, y: y + (ny - y) * t, angle });
    }
  }
  return wp;
}

// softBASIC data module — same path + enemy lists as code (no JSON parser in
// the language). One class; the demo scene does `new StressData()`.
function buildBas(path: ReturnType<typeof buildPath>, enemiesBySize: Record<number, Array<{ x: number; y: number }>>) {
  const L: string[] = ['Class', "' GENERATED by scripts/genRaycasterStress.ts -- do not hand-edit.", ''];
  L.push('dim pathX(0)', 'dim pathY(0)', 'dim pathA(0)');
  for (const n of SIZES) L.push(`dim e${n}x(0)`, `dim e${n}y(0)`);
  L.push('', 'Constructor()');
  for (const w of path) {
    L.push(`  array.push(self.pathX, ${w.x.toFixed(4)})`);
    L.push(`  array.push(self.pathY, ${w.y.toFixed(4)})`);
    L.push(`  array.push(self.pathA, ${w.angle.toFixed(4)})`);
  }
  for (const n of SIZES) {
    for (const e of enemiesBySize[n]) {
      L.push(`  array.push(self.e${n}x, ${e.x.toFixed(2)})`);
      L.push(`  array.push(self.e${n}y, ${e.y.toFixed(2)})`);
    }
  }
  L.push('EndConstructor', '');
  L.push('function pathCount()', '  return array.arrLength(self.pathX)', 'endfunction', '');
  L.push('function px(i)', '  return self.pathX(i)', 'endfunction', '');
  L.push('function py(i)', '  return self.pathY(i)', 'endfunction', '');
  L.push('function pa(i)', '  return self.pathA(i)', 'endfunction', '');
  L.push('function enemyCount(size)');
  for (const n of SIZES) L.push(`  if size = ${n} then`, `    return array.arrLength(self.e${n}x)`, '  endif');
  L.push('  return 0', 'endfunction', '');
  L.push('function ex(size, i)');
  for (const n of SIZES) L.push(`  if size = ${n} then`, `    return self.e${n}x(i)`, '  endif');
  L.push('  return 0', 'endfunction', '');
  L.push('function ey(size, i)');
  for (const n of SIZES) L.push(`  if size = ${n} then`, `    return self.e${n}y(i)`, '  endif');
  L.push('  return 0', 'endfunction', '');
  L.push('EndClass', '');
  return L.join('\n');
}

mkdirSync(OUT, { recursive: true });
const enemiesBySize: Record<number, Array<{ x: number; y: number }>> = {};
for (const n of SIZES) {
  const { stm, walls } = buildStm(n);
  writeFileSync(join(OUT, `stress${n}.stm`), JSON.stringify(stm, null, 2));
  enemiesBySize[n] = buildEnemies(n, walls);
  writeFileSync(join(OUT, `stress${n}.enemies.json`), JSON.stringify(enemiesBySize[n], null, 2));
  console.log(`wrote stress${n}.stm + enemies (${enemiesBySize[n].length})`);
}
const path = buildPath();
writeFileSync(join(OUT, 'stressPath.json'), JSON.stringify(path, null, 2));
writeFileSync('demo-src/raycaster-p9-bench/StressData.bas', buildBas(path, enemiesBySize));
console.log(`wrote stressPath.json (${path.length} wp) + StressData.bas`);
